GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name" : "Russell",
    "surname" : "Johnson",
    "username" : "blueyorange",
    "email" : "blueyorange@gmail.com",
    "dateOfBirth" : "1980-06-28",
    "password" : "plrdzbvq&1"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "blueyorange",
    "password" : "password"
}

###
GET http://localhost:3000/

###

POST http://localhost:3000/users/blueyorange/changepassword
Content-Type: application/json

{
    "_id" : "63249839e6d2692b944f7403",
    "oldPassword" : "plrdzbvq&1",
    "newPassword" : "password"
}